version: '3'
services:
  backend:
    container_name: api
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app  
      - /usr/src/app/node_modules
    build: 
      context: ./backend



  frontend : 
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - usr/src/app/node_modules
   
    build:
      context: ./frontend  


  mongo:
    container_name: mongo_db_container  # Nom personnalisé du conteneur MongoDB
    image: mongo:latest  # Utilise l'image MongoDB officielle
    ports:
      - "27017:27017"  # Expose MongoDB sur le port 27017
    volumes:
      - mongo_data:/data/db  

  

  mongo-express:
    container_name: mongo_express_container
    image: mongo-express:latest
    ports:
      - "8081:8081"  # Expose Mongo Express sur le port 8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo  # Connexion à MongoDB via le service 'mongo'
    depends_on:
      - mongo
    networks:
      - app_network

# Déclaration des réseaux
networks:
  app_network:
    driver: bridge  # Type de réseau utilisé

# Déclaration des volumes
volumes:
  mongo_data:
    driver: local